version: "3.8"
services:
  php-apache-environment:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-apache-bluelock
    image: redlock-web-2.0:latest
    ports:
      - 7077:80

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: redlock
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: KR
        MYSQL_DATABASE: redlock-db
        MYSQL_USER: Geats
        MYSQL_PASSWORD: KR
    ports:
        - 4444:3306